### ISSUE TITLE
Fails to build on M1 mac

### ISSUE THREAD

**Issue by NielsPT** [yquake2/ctf#18]
It the makefile, line 52 is  YQ2_ARCH ?= $(shell uname -m | sed -e 's/i.86/i386/' -e 's/amd64/x86_64/' -e 's/^arm.*/arm/')
This is not correct with current version of clang since 'arm64' will be changed to 'arm', which LD in clang does not understand, so linking fails. Should be YQ2_ARCH ?= $(shell uname -m | sed -e 's/i.86/i386/' -e 's/amd64/x86_64/'). 
I'm only making an issue since I'm not sure how to make a pull request. This is the same issue for xatrix and rogue as well.

**Comment by Yamagi** [comment]
I have pushed a fix. yquake2 itself, xatrix and rogue shouldn't have the problem, though. They use the unaltered `uname -m` output on Macs.
