### ISSUE TITLE
switching weapon while holding grapple still sticks you at grapple destination

### ISSUE THREAD

**Issue by DX37** [yquake2/ctf#6]
Testing CTF with YamagiQ2 7.41, and this happens:
![out](https://user-images.githubusercontent.com/12829428/58718951-c747a480-83f8-11e9-831d-124a4bb4ed67.gif)
(video version [here](https://youtu.be/HiPw2_uIIt8))

Or this is not a bug, but a feature? 😅

**Comment by Yamagi** [comment]
I've tested this with Vanilla Quake II 3.20 and the behavior is the same. I think it's a feature. :)

**Comment by DX37** [comment]
Okay, if you say so :D
